version: "3"

services:
  server:
    build: .
    image: backend:latest
    container_name: server
    ports:
      - "3099:3099"
    depends_on:
      - mongo
    volumes:
      - ./src:/backend/src
    command: npm run start:dev

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

volumes:
  todolist-backend-volume:
