version: "3"

services:
  server:
    image: backend:latest
    container_name: server
    ports:
      - "3099:3099"
    depends_on:
      - mongo
    volumes:
      - ./src:/backend/src

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

volumes:
  todolist-backend-volume:
